### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MildThrone** [Shell1010/Selfcord#13]
can i make documentation for this?
started using it yesterday and expected it to be similar to discord.py, but it's vastly different, finding my way around so far and want to help with the documentation

**Comment by Shell1010** [comment]
This'd be incredibly helpful honestly, I tried to use sphinx before but I kept running into issues.

**Comment by MildThrone** [comment]
Alright, I'll work on it during the week, I'll work with the current features and update along the way.
I'll keep an eye out for the docstring changes as well

**Comment by Shell1010** [comment]
I've attempted to start writing some documentation in https://github.com/Shell1010/Selfcord/wiki, edit it to your hearts content.

**Comment by bl-irtus** [comment]
what
