### ISSUE TITLE
Variable Scope

### ISSUE THREAD

**Issue by MildThrone** [Shell1010/Selfcord#15]
In bot.py, the Bot class uses a "user" member but that's assigned only in the "runner" function so is inaccessible in other functions where referenced (ie. get_guild)
![image](https://user-images.githubusercontent.com/39532762/197604354-2d23ea2b-1b4c-4d1f-b9ac-02e4bce2cc79.png)

**Comment by Shell1010** [comment]
I've not found this issue myself, in the sense I can access the user instance in my testing, even though I get this error myself. I guess I can initialise self.user in the init to help tackle this?

**Comment by MildThrone** [comment]
i did see that in the code but it still returned an AttributeError
