### ISSUE TITLE
Discord invite has expired

### ISSUE THREAD

**Issue by SGtOriginal** [Shell1010/Selfcord#23]
The title is very self descriptive.

**Comment by Shell1010** [comment]
I disagree to agree

**Comment by SGtOriginal** [comment]
Mate, how much more of a destricptive title do you want? I can post a 5 hour read title in here but pretty sure GitHub doesn't allow such big titles.

**Comment by SGtOriginal** [comment]
Well either way the invite in the wiki and the invite in the README.md all show me the invite invalid error on a newly created account that's only 4 months old so I doubt its a problem from my end.

**Comment by SGtOriginal** [comment]
Well??

**Comment by Shell1010** [comment]
im schizophrenic

**Comment by Thegigadev** [comment]
> No shit Sherlock, gimme new invite link.

Quite toxic man, I suggest going outside for a smoke or having a chat with family or smthing

**Comment by SGtOriginal** [comment]
> > No shit Sherlock, gimme new invite link.
> 
> Quite toxic man, I suggest going outside for a smoke or having a chat with family or smthing

?? I just want a new invite link. if you haven't noticed yet its been nearly a week and Shell has not been very helpful.

**Comment by MildThrone** [comment]
https://discord.gg/AevB3DkY
Here you go.
