### ISSUE TITLE
Docstrings and type hints do not show

### ISSUE THREAD

**Issue by Shell1010** [Shell1010/Selfcord#29]
Docstrings and Type hints does not show for selfcord as of right now on my end, and I'm assuming on other users ends too. If you guys can help me find a solution this will be helpful.

**Comment by Shell1010** [comment]
Tested on replit.com and I was able to get docstrings. Ok perhaps an IDE issue then? I use vscode.
![image](https://user-images.githubusercontent.com/72198971/235753292-c73077e5-beae-4df3-9ea0-df72fc6229c7.png)

**Comment by skifli** [comment]
@Shell1010 Works for me on VSCode.
![image](https://github.com/Shell1010/Selfcord/assets/121291719/e4f04974-70b2-4920-b4ed-3aed7720f8a9)

**Comment by Shell1010** [comment]
Have no idea how this fixed itself but it fixed itself.
