### ISSUE TITLE
Hello, how can I send a direct message to someone through a channel using selfcord.py?

### ISSUE THREAD

**Issue by Nalphex** [Shell1010/Selfcord#73]
I've tried this, it didn't work
```py
target_user = await bot.fetch_user(message.author.id)
if target_user:
  await target_user.send(f"How much are you selling {product} for?")
```
it didn't work
![image](https://github.com/Shell1010/Selfcord/assets/76256105/c0198959-7d19-49d0-85a1-db702a625aa9)

**Comment by HaveSechs** [comment]
this may be because sometimes therees a captcha required to send dms

**Comment by Nalphex** [comment]
Hello! If I have a CAPTCHA-solving service, 
how can I integrate it into my script? Specifically, 
if I'm using the CapMonster service

**Comment by Shell1010** [comment]
Use get_user instead, fetch_user gathers from cache and is sync, get_user is an Api request
