### ISSUE TITLE
is there a bot.on("reaction_add")

### ISSUE THREAD

**Issue by Subjoel** [Shell1010/Selfcord#80]
is there something so i can wait until someone reacts to my message and then edit my message when someone reacted?

**Comment by CodecNomad** [comment]
Yes, look in source code!

**Comment by Subjoel** [comment]
i tried finding it, i found bot.py def on()
but i cant find the what the coroutines for on() are.

**Comment by HaveSechs** [comment]
check documentation

**Comment by CodecNomad** [comment]
For once, mini amin is right!

**Comment by Shell1010** [comment]
nope
